name: privacy-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pillow>=11.0.0
  - numpy>=1.24.0
  - requests>=2.31.0
  - pyyaml>=6.0
  - pip:
    - google-genai>=1.44.0
    - google-generativeai>=0.8.5
    - pyautogui>=0.9.54
    - playwright>=1.55.0
    - beautifulsoup4>=4.14.2
    - cachetools>=6.2.1
    - certifi>=2025.10.5
    - charset-normalizer>=3.4.3
    - google-api-core>=2.26.0
    - google-api-python-client>=2.184.0
    - google-auth>=2.41.1
    - google-auth-httplib2>=0.2.0
    - googleapis-common-protos>=1.70.0
    - grpcio>=1.75.1
    - grpcio-status>=1.71.2
    - httplib2>=0.31.0
    - protobuf>=5.29.5
    - proto-plus>=1.26.1
    - pydantic>=2.12.2
    - pydantic-core>=2.41.4
    - regex>=2025.9.18
    - rsa>=4.9.1
    - urllib3>=2.5.0
    - websockets>=15.0.1
    - anyio>=4.11.0
    - h11>=0.16.0
    - httpcore>=1.0.9
    - httpx>=0.28.1
    - sniffio>=1.3.1
    - tenacity>=9.1.2
    - pyee>=13.0.0
    - greenlet>=3.2.4
    # - pyobjc-core>=11.1
    # - pyobjc-framework-Cocoa>=11.1
    # - pyobjc-framework-Quartz>=11.1
    - rubicon-objc>=0.5.2
    - pybind11>=2.12.0
    - pybind11-global>=2.12.0
    - typing-extensions>=4.8.0
    - typing-inspection>=0.4.2
    - annotated-types>=0.7.0
    - packaging>=25.0
    - pyparsing>=3.2.5
    - filelock>=3.13.0
    - fsspec>=2023.10.0
    - gmpy2>=2.3.0
    - mpmath>=1.3.0
    - sympy>=1.12.0
    - optree>=0.11.0
    - scikit-learn>=1.7.2
    - scipy>=1.16.2
    - sentence-transformers>=5.1.1
    - transformers>=4.57.0
    - torch>=2.0.0
    - safetensors>=0.6.2
    - tokenizers>=0.22.1
    - huggingface-hub>=0.35.3
    - tqdm>=4.67.1
    - joblib>=1.5.2
    - threadpoolctl>=3.6.0
    - networkx>=3.0
    - soupsieve>=2.8
    - MouseInfo>=0.1.3
    - PyGetWindow>=0.0.9
    - PyMsgBox>=2.0.1
    - PyRect>=0.2.0
    - PyScreeze>=1.0.1
    - pytweening>=1.2.0
    - pyperclip>=1.11.0
    - Jinja2>=3.1.0
    - MarkupSafe>=2.1.0
    - idna>=3.10
    - uritemplate>=4.2.0
    - pyasn1>=0.6.1
    - pyasn1-modules>=0.4.2
